### ISSUE TITLE
GitHub CI/CD

### ISSUE THREAD

**Issue by alt-art** [newtoallofthis123/lyrics_cli#2]
On my projects, I have the costume to add a CI/CD that helps check bugs and makes generating packages and binaries to releases easier.

You can have clippy lint warnings checks, tests, and code formatting checks directly on GitHub.

And ship packages and deploy them to crates.io with a simple method:

```sh
# Change version on Cargo.toml
# Commit
git commit -m "Bump to 0.2.0"
# Gen a tag
git tag 0.2.0
# push commit with tag
git push && git push --tags
```

Now, actions will do all the work for you, compiling the code and generating the packages. When everything is finished, you can publish the version with the files on the releases pages by taking the draft that the action made.

**Comment by alt-art** [comment]
The CI/CD will be made by having action configurations on this project and a release script.

Example: https://github.com/alt-art/commit

**Comment by newtoallofthis123** [comment]
Interesting Idea @alt-art. I have actually considered this in the past. However, my knowledge of GitHub actions is limited.

If you are interested in contributing, please do so. This seems like a good idea!
